In [1]:
import pandas as pd
import numpy as np

from random import randrange

In [2]:
df = pd.read_csv('data/day.csv')
df.head()

instant      dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  2011-01-01       1   0     1        0        6           0   
1        2  2011-01-02       1   0     1        0        0           0   
2        3  2011-01-03       1   0     1        0        1           1   
3        4  2011-01-04       1   0     1        0        2           1   
4        5  2011-01-05       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  casual  registered  \
0           2  0.344167  0.363625  0.805833   0.160446     331         654   
1           2  0.363478  0.353739  0.696087   0.248539     131         670   
2           1  0.196364  0.189405  0.437273   0.248309     120        1229   
3           1  0.200000  0.212122  0.590435   0.160296     108        1454   
4           1  0.226957  0.229270  0.436957   0.186900      82        1518   

    cnt  
0   985  
1   801  
2  1349  
3  1562  
4  1600

In [3]:
df = df[['temp', 'atemp', 'hum', 'windspeed']]
df = df[:-1]
df.shape

(730, 4)

In [30]:
# Define the w and T
T = 10
w = df.shape[0] // T

# N is number of states
N = 5

print('w, T = ', w, T)
print('N = ', N)

w, T =  73 10
N =  5


In [31]:
# Split the data into a wxT numpy matrix
sequences = df.values
sequences = sequences.reshape(w, T, df.shape[1])
sequences.shape

(73, 10, 4)

In [32]:
states = [[randrange(0, sequences.shape[0]*sequences.shape[1])] for state in range(0, N)]
states


[[398], [123], [225], [381], [63]]

In [33]:
centroid_of_states = [sequences[x[0]//T][x[0]%T] for x in states]
centroid_of_states

[array([ 0.313333,  0.309346,  0.526667,  0.178496]),
 array([ 0.414167,  0.40465 ,  0.737083,  0.328996]),
 array([ 0.676667,  0.624388,  0.8175  ,  0.222633]),
 array([ 0.373043,  0.364278,  0.716087,  0.34913 ]),
 array([ 0.384167,  0.378779,  0.789167,  0.251871])]

In [34]:
assigned_states = np.array(np.zeros((w, T)))
for i in range(1, N+1):
    x = states[i-1][0] // T
    y = states[i-1][0] % T
    assigned_states[x][y] = i


In [35]:
for i in range(0, w):
    for j in range(0, T):
        if assigned_states[i][j] == 0:
            
            min_dist = np.linalg.norm(centroid_of_states[0] - sequences[i][j])
            min_idx = 0
            for k in range(1, N):
                dist_from_centroid = np.linalg.norm(centroid_of_states[k] - sequences[i][j])
                if min_dist > dist_from_centroid:
                    min_dist = dist_from_centroid
                    min_idx = k
            
            state_idx = min_idx
            
            centroid_of_states[state_idx] = (centroid_of_states[state_idx] * len(states[state_idx]) + sequences[i][j]) / (len(states[state_idx]) + 1)
            states[state_idx].append((i*T + j))
            assigned_states[i][j] = state_idx + 1
            


In [36]:
len(states[0]) + len(states[1]) + len(states[2]) + len(states[3]) + len(states[4]) 

730

In [53]:
# Calculate initial probabilities
pi_vector = [0 for i in range(0, N)]

observations_all, counts_total = np.unique(df.values, axis=0, return_counts=True)

counts_o1 = 0    
for i in range(0, w):
    O1 = sequences[i][0]
    
    for state in states:
        state_vector = [sequences[idx // T][idx % T] for idx in state]
        
        observations, counts = np.unique(state_vector, axis=0, return_counts=True)
        idx = np.where(np.all(observations == O1, axis=1))
        
        if len(idx[0]) != 0:
            pi_vector[states.index(state)] += counts[idx[0][0]]

    idx = np.where(np.all(observations_all == O1, axis=1))
    counts_o1 += counts_total[idx[0][0]]

pi_vector = pi_vector / counts_o1
pi_vector


array([ 0.21917808,  0.15068493,  0.36986301,  0.12328767,  0.1369863 ])

In [54]:
# Calculate transition probabilities
a_matrix = [[0 for i in range(0, N)] for j in range(0, N)]

for k in w:
    for i in range(0, N):
        for j in range(0, N):
            for 

SyntaxError: unexpected EOF while parsing (<ipython-input-54-031d5d2e0dd8>, line 6)